allow to continue run tests even if ruche CI fails
kokkos/kokkos-fft pull request #193
Opened 2024-11-04 11:07 UTC by yasahi-hpc

In this RP, we allow to continue run tests even if ruche CI fails.

2024-11-05 10:59 UTC, tpadioleau commented
I still think it is worth it, we should try to make it work at some point

2025-01-08 09:00 UTC, tpadioleau requested changes

2025-01-08 09:00 UTC, tpadioleau commented on .github/workflows/build_test.yaml
> +            unstable: true
Was it meant to override `matrix.unstable` ? If I understand correctly this creates a new variable `matrix.backend.unstable` ?

I think we need an entry for each backend ?

2025-01-08 09:19 UTC, yasahi-hpc commented on .github/workflows/build_test.yaml
> +            unstable: true
Thank you for the comments.

Ah, that is true. We need to introduce `matrix.backend.unstable` rather than `matrix.unstable`

2025-01-08 11:18 UTC, tpadioleau approved these changes
Ok let's try!

2025-01-08 11:23 UTC, yasahi-hpc commented
@tpadioleau Thanks again for the review.
Fortunately or unfortunately, ruche CI worked this time. 
Hopefully after merging this, CI continues even if ruche CI fails

2025-01-08 11:23 UTC, merged