Add advanced example
kokkos/kokkos-fft pull request #198
Opened 2024-11-10 11:00 UTC by yasahi-hpc

Resolves #60 

This PR aims at adding an advanced example to solve 2D Hasegawa-Wakatani equation with the spectral method.

- [x] Baseline implementation in c++ and python
- [ ] Detailed documentations
- [ ] Adding diagnostics

2025-03-11 11:00 UTC, tpadioleau requested changes
This is an interesting example.

I tried to run the example but I got an out of bound access of the array `mask`.

2025-03-12 12:53 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +using execution_space = Kokkos::DefaultExecutionSpace;
Type could be PascalCase.

2025-03-12 16:57 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/README.md
> +* `rocm 5.3.0+` (AMD GPUs)
I added a comment to see README for the latest modules

2025-03-12 16:59 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/io_utils.hpp
That is interesting and probably a better way.
Can I do this in another PR, since this helper is not the most important part

2025-03-12 16:59 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    }
I have updated accordingly

2025-03-13 05:41 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/io_utils.hpp
It seems working

2025-03-13 06:13 UTC, yasahi-hpc commented
@tpadioleau 
Thank you for your review.
I have fixed accordingly. 
May I have another review please

2025-03-13 08:34 UTC, tpadioleau reviewed
A few minor comments

2025-03-13 08:34 UTC, tpadioleau commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    const auto* dydt_data = dydt.data();
Why do we need to work with pointers ? I don't feel we should show this in the blog

2025-03-13 08:34 UTC, tpadioleau commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +                            Kokkos::exp(I * 2.0 * M_PI * random_number);
```suggestion
                            Kokkos::exp(I * 2.0 * Kokkos::numbers::pi * random_number);
```

2025-03-13 08:34 UTC, tpadioleau commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    }
What about using a MDRangePolicy on the `DefaultExecutionSpace` if we use `KokkosFFT::fftfreq(execution_space(), nkx2, dkx)` ?

2025-03-13 08:34 UTC, tpadioleau commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +          KOKKOS_LAMBDA(const int& i) {
```suggestion
          Kokkos::RangePolicy<execution_space, Kokkos::IndexType<int>>(
              execution_space(), 0, m_array_size),
          KOKKOS_LAMBDA(const int& i) {
```

Or the reverse.

Same for the other loops.

2025-03-13 08:41 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    }
If we call the GPU kernels in a constructor, it does not compile on NVIDIA GPUs. So, I would like to initialize on host and copy back to device.

2025-03-13 08:41 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +                            Kokkos::exp(I * 2.0 * M_PI * random_number);
Sure

2025-03-13 08:44 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    const auto* dydt_data = dydt.data();
I use pointers for two reasons: performance and simplicity.
Because the `y` and `dydt` can be multidimensional, we need MDRange for computations. However, for time advances, the dimensionally of variables does not matter

2025-03-13 08:44 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +          KOKKOS_LAMBDA(const int& i) {
Sure

2025-03-13 09:30 UTC, tpadioleau commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +          };
```suggestion
          }
```

2025-03-13 09:41 UTC, tpadioleau commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    const auto* dydt_data = dydt.data();
In case the user passes a LayoutStride we cannot ensure the result to be correct, right ?

I suggest the caller/user of this class is responsible to construct and pass 1D Views so that we can work with the function call operator.

2025-03-13 10:01 UTC, tpadioleau commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    }
I see, I guess the proper way would be create free functions to do this work.

Let's keep it like that for now.

2025-03-13 13:07 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +  View1D<double> m_kyh;
Why the h in the variable name? Does it signify "hat"? A brief comment about it would be useful for the reader.

2025-03-13 13:13 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +  //! Grid in x and y direction (nky + 1, nkx * 2 + 1)
You could add a small note that a coordinate has the order (y, x) and not the usual (x, y).

2025-03-13 13:14 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +  View1D<double> m_kyh;
It is a little bit complicated. 
Since the original variable `f` is a real variable, we have Hermitian symmetry for its Fourier representation. Thus, we use only half domain in y direction. 

I may add this in README.md

2025-03-13 13:19 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    int nkx2 = nkx * 2 + 1, nky2 = nky * 2 + 1, nkyh = nky + 1;
Why are nkx, nky, nkx2, nky2 and nkyh computed this way? In case, they are described in the README, a reference to the section in the README would be useful.

For a user, who wants to use this code as a step-by-step guide to get started with kokkos-fft, this will be useful. The tutorials by Mark Harris on CUDA generally mentions everything in detail. I feel that is good in the context of an introductory and hands-on tutorial.

2025-03-13 13:27 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    m_pk = View2D<Kokkos::complex<double>>("pk", nkyh, nkx2);
Why is the potential field only zero initialized?

2025-03-13 13:30 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +// t^{n+1} = t^{n} + h
`f(t, y) by ...` is not clear.

2025-03-13 13:35 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +  using float_type     = KokkosFFT::Impl::base_floating_point_type<value_type>;
Why is the `float_type` obtained as `KokkosFFT::Impl::base_floating_point_type<value_type>`?

2025-03-13 13:36 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +  BufferViewType m_y, m_k1, m_k2, m_k3;
Why no `m_k4`?

2025-03-13 13:41 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    int nkx2 = nkx * 2 + 1, nky2 = nky * 2 + 1, nkyh = nky + 1;
It is basically for aliasing. 
What we would like to compute is the following computational domain `[-nkx, nkx]`
However, the code can contaminate the domain of `[-nkx*2, nkx*2]` due to the alias.
For efficiency, we can add a buffer region of length `nkx` to the original domain to have `[-nkx, nkx*2]`,
where the region `[nkx, nkx*2]` is used as a buffer region for both positive and negative frequency. 
In the end, we need the domain `[0, nx]` to cover `[-nkx, nkx*2]`.
Thus, we got the following relationship `nx >= nkx * 3`

2025-03-13 13:42 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    constexpr int nb_vars = 2;
True

2025-03-13 13:43 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +  //! Grid in x and y direction (nky + 1, nkx * 2 + 1)
Because the variables are in `LayoutRight`

2025-03-13 13:46 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    m_pk = View2D<Kokkos::complex<double>>("pk", nkyh, nkx2);
They are initialized on GPUs later

2025-03-13 13:46 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +  std::size_t m_array_size;
Could you give this variable another name? Maybe, `m_flat_size`.

2025-03-13 13:47 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +// t^{n+1} = t^{n} + h
In my notation, `t = n \Delta t`, where `n` is an index for time

2025-03-13 13:48 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +  using float_type     = KokkosFFT::Impl::base_floating_point_type<value_type>;
I would like to use the same precision for the input view

2025-03-13 13:52 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +  BufferViewType m_y, m_k1, m_k2, m_k3;
You could also clarify that they are all stored in a flat manner.

2025-03-13 13:55 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +  View1D<double> m_kyh;
Thank you for the clarification.

Yes, it will be good to have:
1. A more detailed README.
2. Comments here with references to the appropriate sections/equations.

2025-03-13 13:56 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +  //! Grid in x and y direction (nky + 1, nkx * 2 + 1)
Thank you for the clarification.

Don't lose time replying to my comments. Consider adding comments in the code to guide the reader.

2025-03-13 14:00 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    int nkx2 = nkx * 2 + 1, nky2 = nky * 2 + 1, nkyh = nky + 1;
Thank you again for the clarification. Please don't lose time replying to my comments. Add the text to the README or as comments in the code.

2025-03-13 14:04 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    static_assert(ViewType::rank == 1, "RK4th: ViewType must have rank 1.");
You could add a comment in the function description that the function is expecting flattened 1D versions of the multi-dimensional arrays.

2025-03-13 14:08 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +// Force A to satisfy the following conditios
typo: conditions.

2025-03-13 14:08 UTC, yasahi-hpc commented
@tpadioleau Thanks again. I have updated accordingly

@science-enthusiast I will make another PR to improve docs. Anyway I need to refer this example in the documentation and also I am inclined to add a movie. 

As for the very numerical details, I also need not to explain too much. I expect that many people are not interested in the numerics

2025-03-13 14:13 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +// \param mask The mask view [0, 1, 1, ..., 1] (nkx + 1)
If the mask view is always a 1D array, with 0 followed by nkx 1s, do you need to accept it as an argument?

2025-03-13 14:22 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +            execution_space(), 0, nk1 + 1),
Is nvars big enough? If so maybe an MDRangePolicy would be good here. If an outside user sees that again and again MDRangePolicy is not being used where it can be used, they will wonder whether something is wrong with MDRangePolicy.

2025-03-13 14:23 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +          view(dst_idx) = mask(i0) * Kokkos::conj(tmp_view);
What is `Kokkos::conj`? I am not able to find it in the documentation also.

2025-03-13 14:29 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +            execution_space(), 0, nk1 + 1),
Well, nvars is 2, so it is OK to use RangePolicy here

2025-03-13 14:30 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +          view(dst_idx) = mask(i0) * Kokkos::conj(tmp_view);
Equivalent to `std::conj` computing complex conjugate. Maybe they just rely on the specification of standard

2025-03-13 14:50 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    m_variables = std::make_unique<Variables>(*m_grid);
You can initialize the unique_ptr member variables in the member-initializer list itself.

2025-03-13 15:04 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    m_norm_coef           = static_cast<double>(m_nx * m_ny);
These scalar variables could also be initialized in the member initializer list.

2025-03-13 15:11 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    }
Consider using `Kokkos::Experimental::fill`.

2025-03-13 15:16 UTC, yasahi-hpc commented
@science-enthusiast Thank you for your review.
Can I merge this now. I will open another PR to improve the code and docs.

I would like to initiate the blog post PR on top of this

2025-03-13 15:30 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    realityCondition(sub_pk, m_mask);
It is not clear why realityCondition is being checked in the constructor. One thinks only initializations happen in the constructor.

2025-03-13 15:30 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +  void diag_fields(const int iter) {
Saving data is considered as diagnostics here

2025-03-13 15:31 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +    realityCondition(sub_pk, m_mask);
It is not checking but forcing the reality condition.

2025-03-13 15:35 UTC, science-enthusiast commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +  std::unique_ptr<BackwardPlanType> m_backward_plan;
Also it is not yet clear why they have to be unique_ptrs to objects of those types? Why not have members of those types?

2025-03-13 15:43 UTC, yasahi-hpc commented on examples/10_HasegawaWakatani/10_hasegawa_wakatani.cpp
> +  std::unique_ptr<BackwardPlanType> m_backward_plan;
Because it is more flexible when initializing

2025-03-13 15:51 UTC, merged

2025-03-13 19:09 UTC, science-enthusiast commented
My comments regarding the implementation could be addressed later. It will be good if the comments regarding more information in the README and code comments are addressed soon.