Introduce Kokkos::Profiling::Region to profile tpl calls
kokkos/kokkos-fft pull request #204
Opened 2024-11-28 08:41 UTC by yasahi-hpc

Resolves #201 

In this PR, we introduce `Kokkos::Profiling::pushRegion` to profile the timings of tpl calls.

2024-11-28 12:19 UTC, dalg24 reviewed
I didn't look at all the changes but the one I saw were a better fit for [`Kokkos::Profiling::ScopedRegion`](https://kokkos.org/kokkos-core-wiki/API/core/profiling/scoped_region.html)

2024-11-28 13:10 UTC, yasahi-hpc commented
> I didn't look at all the changes but the one I saw were a better fit for [`Kokkos::Profiling::ScopedRegion`](https://kokkos.org/kokkos-core-wiki/API/core/profiling/scoped_region.html)

Thank you for the comments. I was not aware of this. 
Clearly, this is what I need

2025-01-24 17:33 UTC, rb214678 requested changes
Except my small cosmetic question/comment, this looks good to me.

2025-01-25 07:28 UTC, yasahi-hpc commented on fft/src/KokkosFFT_Transform.hpp
True. I modified to an empty line if there are some operations before.

2025-01-25 07:29 UTC, yasahi-hpc commented
@rb214678 Thank you for the review. I have fixed accordingly.

2025-01-27 08:24 UTC, rb214678 approved these changes

2025-01-27 08:26 UTC, rb214678 approved these changes

2025-01-27 08:27 UTC, rb214678 commented on fft/src/KokkosFFT_Transform.hpp
Ok, thanks for the changes.

2025-01-27 08:37 UTC, merged